# Worker
FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY api/package.json ./api/
COPY shared/package.json ./shared/
COPY web/package.json ./web/
COPY worker/package.json ./worker/
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build -w shared && npm run build -w worker
RUN npx tsc-alias -p worker/tsconfig.build.json --resolve-full-paths || true

FROM node:22-alpine AS app
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/worker/dist ./worker/dist
COPY --from=builder /app/worker/package.json ./worker/
COPY --from=builder /app/shared ./shared
COPY --from=builder /app/package.json ./
ENTRYPOINT ["npm", "run"]
CMD ["start:worker:prod"]
