server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /sorting-table/api/ {
    proxy_pass http://api:3019/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /sorting-table {
    rewrite ^/sorting-table/?(.*)$ /$1 last;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
